### ISSUE TITLE
Separate card pool OT vs WWE

### ISSUE THREAD

**Issue by stopfstedt** [townteki/dtdb#11]
in order to make interface improvements that will allow our users from easily separating the Old from the New (primarily for deck-building and deck-searching purposes), we'll need to add a flag somewhere to the data set.

could be at the pack level, or at the card level (to be determined).

**Comment by stopfstedt** [comment]
probably at the card level. would be helpful to know what's actually in scope for old-timer vs. weird west edition. 

is the split between those formats/card-pools exactly along the lines of AEG-era cards vs Pinebox cards now? or is there some overlap.

**Comment by mmeldo** [comment]
yeah, I will first check with Lapp to make sure what exactly is "Old Timer" format, because WWE I am sure is from TCaR upward.
I would rather specify the format at the pack level, because there are no individual cards fitting WWE format that are in old-timer packs. I know it will be little bit more work to check if card is in particular format since we first have to get the pack, but I believe that is not a problem.

What is a problemn though is that I did not finish card validation checking on DTO side. It still uses _restricted lists_ from throneteki which do not really fit how doomtown is doing things. So I will have to also figure out what to do there.

But I believe we can proceed with updating packs/cards (depending how we decide) and I will solve the DTO side later.

**Comment by mmeldo** [comment]
I guess you have seen my question in Discord, but I will put it also here for reference:
__WWE__ - deck is in this format if all cards are from pack TCaR or later (basically only from packs published by PBE)
__Old Timer__ - if deck is not in WWE format, meaning it has at least one card from pack before TCaR, but it does not matter if it has some cards from WWE pack

**Comment by stopfstedt** [comment]
thanks @mmeldo - that's our answer. based on that feedback, i'm not going to pursue this any further, at least not at this point. since there is not clear line that separates OT from WWE that can be expressed in such a way.
instead, we'll have to make that distinction in code.
